name: MasterDeployCI
on:
  push:
    branches:
      - kellyos_main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r nckos_debug.zip . -x ".git/*" ".github/*" ".md" "LICENSE"
